### PR TITLE
Overall unification of translations strings

### PR DESCRIPTION
**Pull request by Nickoriginal**
Make their places to match other languages places, also add commentaries where they placed in other .xml strings

### CODE REVIEW

**Comment by Nickoriginal** [comment]
Also add commentaries where they placed in other .xml strings

**Comment by m-i-n-a-r** [comment]
Thanks! I'll release this as soon as I can 👍

**Comment by Nickoriginal** [comment]
It is draft, because I want to do this for many languages!

**Comment by Nickoriginal** [comment]
Also @m-i-n-a-r do you want to keep [this](https://github.com/m-i-n-a-r/randomix/blob/master/app/src/main/res/values-cs/strings.xml#L1) line in all translations?

**Comment by m-i-n-a-r** [comment]
It should be needed, but i still don't understand if it's mandatory. Removing it shouldn't cause issues, i guess.

**Comment by Nickoriginal** [comment]
OK, thanks!

**Comment by Nickoriginal** [comment]
It is ready now!

**Comment by m-i-n-a-r** [comment]
Thanks!

**Pull request merged**
