### PR TITLE
Update Asturian translation

### PR DESCRIPTION
**Pull request by softastur**
This commit updates Asturian translation and removes some trolling strings translated into Spanish by someone who, I would like to think, were confused.

### CODE REVIEW

**Comment by m-i-n-a-r** [comment]
Thanks!

**Comment by m-i-n-a-r** [comment]
As a side note, there are still untranslated asturian strings, you can find them in Crowdin, here https://crowdin.com/project/randomix

**Comment by softastur** [comment]
Oh! I didn't know this project were on Crowdin, I was translating the app locally but the app is fully translated

**Comment by m-i-n-a-r** [comment]
No problem, i activated the bi-directional sync with Github and your translations were successfully imported in Crowdin 😄

**Pull request merged**
